<?php

    namespace App\Models;


    class ConfigurationDecoratorCache extends ConfigurationDecoratorBase
    {
        public function readData(): string
        {
            parent::readData(); // TODO: Change the autogenerated stub
        }

        public function writeData(): bool
        {
            parent::writeData(); // TODO: Change the autogenerated stub
        }
    }