<?php


    namespace App\Models;


    class ConfigurationDecoratorEnvironment extends ConfigurationDecoratorBase
    {
        public function readData(): array
        {
            parent::readData(); // TODO: Change the autogenerated stub
        }
        public function writeData(): bool
        {
            parent::writeData(); // TODO: Change the autogenerated stub
        }
    }